app:
  image: vfarcic/books-ms
  ports:
    - 8080
  environment:
    - SERVICE_NAME=books-ms
    - DB_HOST=books-ms-db

app-blue:
  environment:
    - SERVICE_NAME=books-ms-blue
  extends:
    service: app

app-green:
  environment:
    - SERVICE_NAME=books-ms-green
  extends:
    service: app

db:
  container_name: books-ms-db
  image: mongo
  environment:
    - SERVICE_NAME=books-ms-db

tests:
  image: vfarcic/books-ms-tests
  volumes:
    - ./client/components:/source/client/components
    - ./client/test:/source/client/test
    - ./src:/source/src
    - ./target/scala-2.10:/source/target/scala-2.10
    - ./client/wct-complete.conf.js:/source/client/wct.conf.js
    - /data/tests/db:/data/db
  environment:
    - TEST_TYPE=all

integ:
  image: vfarcic/books-ms-tests
  volumes:
    - ./src:/source/src
  environment:
    - TEST_TYPE=integ
    - DOMAIN=$DOMAIN