home: /data/jenkins

jobs: [
  {
    name: "books-ms",
    service_name: "books-ms",
    repo: "vfarcic/blue-green-docker-jenkins",
    src: "service-workflow-config.xml",
    ping_address: "/api/v1/books"
   }
]

plugins:
  - git
  - workflow-aggregator
  - docker-workflow